status = [
    "Linux (runtime/cpp)",
    "CentOS (7, runtime/cpp)",
    "CentOS (8, runtime/cpp)",
    "CentOS (8, codegen/cpp/fletchgen)",
    "Ubuntu (18.04, runtime/cpp)",
    "Ubuntu (18.04, codegen/cpp/fletchgen)",
    "Ubuntu (20.04, runtime/cpp)",
    "Ubuntu (20.04, codegen/cpp/fletchgen)",
    "Python (codegen/python, 2014, cp36-cp36m)",
    "Python (codegen/python, 2014, cp37-cp37m)",
    "Python (codegen/python, 2014, cp38-cp38)",
    "Python (codegen/python, 2014, cp39-cp39)",
    "Python (runtime/python, 2014, cp36-cp36m)",
    "Python (runtime/python, 2014, cp37-cp37m)",
    "Python (runtime/python, 2014, cp38-cp38)",
    "Python (runtime/python, 2014, cp39-cp39)",
    "Check Markdown links",
    "Book",
    "C++ (fletchgen, codegen/cpp/fletchgen)",
    "C++ (runtime, runtime/cpp)",
    "Prepare",
    "Test (examples/stringwrite/hardware)",
    "Test (examples/sum/hardware)",
    "Test (codegen/test/primmap)",
    "Test (codegen/test/stringread)",
    "Test (codegen/test/listprim)",
    "C++ (codegen/cpp/fletchgen)",
    "C++ (runtime/cpp)",
    "C++ (platforms/echo/runtime)",
    "Python (runtime/python)",
    "Python (codegen/python)",
    "VHDL"
]
delete_merged_branches = true
